### ISSUE TITLE
Tables and Attributes

### ISSUE THREAD

**Issue by Syrkres** [valentine195/obsidian-markdown-attributes#7]
**Describe the bug**
When trying to add an attribute to a nested table in a blockquote (haven't tried nesting in other elements) it does not properly pick up attribute/class.

I've tried several different ways to add it, both nested in the blockquote 
> {.myclass}   // nested in blockquote under table
{.myclass}   // not netsed in blockquote.

**Markdown Source**
> |`dice: 1d8`| Item Carried for pick pocketed |
> | :---:| :--- |
> |0 | Worn Glass Cutter  | 
> |1 | Cherry wood dog whistle  | 
> |2 | Brown conch shell  | 
> |3 | Small linen purse made of hide  | 
> |4 | Rolled Tobacco  | 
> |5 | Steal Chain with 4x Steal keys    | 
> |6 | 1x Gecko scales  | 
> |7 | 2x Small Lizard scales  | 
 { .mytable }

**Screenshots**
Just doesn't apply table, but rather creates a p (paragraph) element with the class name.
![image](https://user-images.githubusercontent.com/99834871/154340663-426f532b-fefd-43ba-bc3b-13dc0818ea04.png)

**Comment by sigrunixia** [comment]
It appears there may be a more extensive issue with tables. 

Test CSS.

```css
.table-test {
    color: crimson;
    background-color: #00ff00;
    border: 1px solid #000000;
    border-radius: 1em;
    padding: 1em;
    margin: 1em;
    width: 50%;
    height: 50%;
    overflow: auto;
    box-shadow: 0.1em 0.1em 0.1em #000000;
    opacity: 0.5;
}
```

Test Markdown File:
[Issue 7 - Table Test.md](https://github.com/javalent/markdown-attributes/files/11324760/Issue.7.-.Table.Test.md)


Attributes only took effect for width, when applied to header.
